---
kind: pipeline
type: docker
name: godtone-app

clone:
  git:
    image: plugins/git
    tags: true

steps:
- name: publish-to-docker-hub
  image: plugins/docker
  dockerfile: ./Dockerfile
  settings:
    auto_tag: true
    cache_from: weeee9/godtone
    repo: weeee9/godtone
    username: 
      from_secret: DOCKER_HUB_USERNAME
    password: 
      from_secret: DOCKER_HUB_PASSWORD

- name: publish-to-gcr
  image: plugins/gcr
  dockerfile: ./Dockerfile
  settings:
    auto_tag: true
    registry: asia.gcr.io
    cache_from: asia.gcr.io/godtone/godtone
    repo: asia.gcr.io/godtone/godtone
    json_key:
      from_secret: GAE_CREDENTIALS

- name: deploy
  image: nytimes/drone-gae
  settings:
    action: deploy
    app_file: app.yaml
  environment:
    GAE_CREDENTIALS:
      from_secret: GAE_CREDENTIALS

# - name: deploy-to-gce
#   image: google/cloud-sdk:alpine
#   environment:
#     json_key:
#       from_secret: GCR_CREDENTIAL
#   commands:
#     - echo $${json_key} > /tmp/cred.json
#     - gcloud auth activate-service-account deploy@godtone.iam.gserviceaccount.com --key-file /tmp/cred.json
#     - gcloud config set project godtone
#     - gcloud compute instances update-container godtone --zone asia-east1-b --container-image=asia.gcr.io/godtone/godtone:latest